default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: 07081981
  host: 127.0.0.1


development:
  <<: *default
  database: postgres
  port: 5432

test:
  <<: *default
  database: nome_do_seu_banco_de_dados_test
  port: 5432

production:
  <<: *default
  database: nome_do_seu_banco_de_dados_production
  port: 5432
